### ISSUE TITLE
File uploads are not supported

### ISSUE THREAD

**Issue by optimiSupport** [CallumBoase/knack-api-helper#6]
PROBLEM: file uploads to Knack happen in 2 stages (see https://docs.knack.com/docs/fileimage-uploads)
If we were uploading a file to the Knack API right now, we'd need to use some other library to handle stage 1 (uploading the file to AWS) and then step 2 could be handled via knack-api-helper.

SOLUTION:
Add a method for handling file uploads via knack-api-helper

**Comment by CallumBoase** [comment]
Fixed with version 2.3.0 release.
